public class Main {
    public static void main(String[] args) {
        var dog = 8.0;
        System.out.println(dog);
        var cat = 3.6;
        System.out.println(cat);
        var paper = 763789;
        System.out.println(paper);
        dog = dog + 4;
        System.out.println(dog);
        cat = cat + 4;
        System.out.println(cat);
        paper = paper + 4;
        System.out.println(paper);
        dog = dog - 3.5;
        System.out.println(dog);
        cat = cat - 1.6;
        System.out.println(cat);
        paper = paper - 7639;
        System.out.println(paper);
        var friend = 19;
        System.out.println(friend);
        friend = friend * 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        var weightBoxerOne = 78.2;
        var weightBoxerTwo = 82.7;
        var weightBoxers = weightBoxerOne + weightBoxerTwo;
        System.out.println("Общая масса двух бойцов " + weightBoxers);
        var lightWeight = weightBoxerOne - weightBoxerTwo;
        System.out.println("Разница между бойцами составит " + lightWeight + " кг");
        var lightWeightBoxers = weightBoxerTwo % weightBoxerOne;
        System.out.println(lightWeightBoxers);
        var workHours = 640;
        var personHours = 8;
        var persons = workHours / personHours;
        System.out.println ("Всего работников в компании - " + persons + " человек");
    persons = persons + 94;
    workHours = persons * personHours;
    System.out.println ("Если в компании работает " + persons + " человек, то всего " + workHours + " часов работы может быть поделено между сотрудниками.");
    }
}